[tox]
envlist = docs
skipsdist = true

[testenv:qiskit-docs]
deps = -r requirements-qiskit.txt
commands = python scripts/generate_demo_outputs.py --framework qiskit {posargs}

[testenv:cirq-docs]
deps = -r requirements-cirq.txt
commands = python scripts/generate_demo_outputs.py --framework cirq {posargs}

[testenv:docs]
deps = -r requirements-docs.txt
commands =
    python scripts/render_docs.py
    mkdocs build
